#include "../types/types.h"
#include "../token/position.h"
#include "../token/token.h"

// name of every token
const char * const symbols[] = {
  [TOKEN_EOF]       = "EOF",
  [TOKEN_SPACE]     = "SPACE",
  [TOKEN_NOT]       = "!",	
  [TOKEN_QUTA]      = "\"",	
  [TOKEN_HASH]      = "#",	
  [TOKEN_DOLLER]    = "$",
  [TOKEN_PERCENT]   = "%",
  [TOKEN_AND]       = "&", 	
  [TOKEN_PRIME]     = "'",	
  [TOKEN_LPAREN]    = "(",	
  [TOKEN_RPAREN]    = ")",	
  [TOKEN_STAR]      = "*",	 
  [TOKEN_PLUS]      = "+",	 
  [TOKEN_COMMA]     = ",",	
  [TOKEN_MINUS]     = "-",	
  [TOKEN_DOT]       = ".",
  [TOKEN_SLASH]     = "/",
  [TOKEN_COLON]     = ":",	
  [TOKEN_SEMICOLON] = ";",
  [TOKEN_LT]        = "<",
  [TOKEN_EQ]        = "=",	
  [TOKEN_GT]        = ">",	 
  [TOKEN_QUESTION]  = "?", 
  [TOKEN_AT]        = "@",  
  [TOKEN_LBRACKET]  = "[", 
  [TOKEN_BACKSLASH] = "\\",
  [TOKEN_RBRACKET]  = "]", 
  [TOKEN_CARET]     = "^",	 
  [TOKEN_UNDERLINE] = "_",
  [TOKEN_UPRIME]    = "`",	
  [TOKEN_LBRACE]    = "{",	
  [TOKEN_OR]        = "|",	
  [TOKEN_RBRACE]    = "}",	 
  [TOKEN_TILDE]     = "~",

  [TOKEN_ID]        = "identifier",
  [TOKEN_NUMBER]    = "number",
  [TOKEN_CHAR]      = "char",
  [TOKEN_STRING]	  = "string",

  [TOKEN_CONTINUE_KEYWORD]  = "continue",
  [TOKEN_BREAK_KEYWORD]     = "break",
  [TOKEN_ELSE_KEYWORD]      = "else",
  [TOKEN_IF_KEYWORD]        = "if",
  [TOKEN_TRY_KEYWORD]       = "try",
  [TOKEN_CATCH_KEYWORD]     = "catch",
  [TOKEN_THROW_KEYWORD]     = "throw",
  [TOKEN_IMPORT_KEYWORD]    = "import",
  [TOKEN_FROM_KEYWORD]    	= "from",
  [TOKEN_RETURN_KEYWORD]    = "return",
  [TOKEN_TRUE_KEYWORD]      = "true",
  [TOKEN_FALSE_KEYWORD]     = "false",
  [TOKEN_FOR_KEYWORD]       = "for",
  [TOKEN_IN_KEYWORD]        = "in",
  [TOKEN_SIZEOF_KEYWORD]    = "sizeof",
  [TOKEN_TYPEOF_KEYWORD]    = "typeof",
  [TOKEN_NULL_KEYWORD]      = "null",
  [TOKEN_FUNC_KEYWORD]      = "func",
  [TOKEN_CLASS_KEYWORD]     = "class",
  [TOKEN_EXTENDS_KEYWORD]   = "extends",
  [TOKEN_ASYNC_KEYWORD]     = "async",
  [TOKEN_AWAIT_KEYWORD]     = "await",
  [TOKEN_STATIC_KEYWORD]    = "static",
  [TOKEN_PUBLIC_KEYWORD]    = "public",
  [TOKEN_PRIVATE_KEYWORD]   = "private",
  [TOKEN_PROTECTED_KEYWORD] = "protected",
  [TOKEN_READONLY_KEYWORD]  = "readonly",
  [TOKEN_VAR_KEYWORD]     	= "var",
  [TOKEN_CONST_KEYWORD]     = "const",
  [TOKEN_TYPE_KEYWORD]     	= "type",
  [TOKEN_ENUM_KEYWORD]     	= "enum",
  [TOKEN_NAMESPACE_KEYWORD] = "namespace",
  [TOKEN_EXPORT_KEYWORD]    = "export"
};

const char *
token_get_name(int32_t tp){
    return symbols[tp];
}